# Generated by Django 5.1.1 on 2024-10-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=15)),
                ('count', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('company_name', models.CharField(max_length=15)),
                ('dicount', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
    ]
